# Constants for padding, distances, etc.
PADDING_TOP = 30
MARKING_OFFSET = 10
OBJECT_PADDING = 60
TITLE_FONT_SIZE = 36
OBJECT_FONT_SIZE = 24
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
MIRROR_DEFAULT_SIZE = 100
ROTATION_SPEED = 90