# Constants for padding, distances, etc.
PADDING_TOP = 30
MARKING_OFFSET = 10
OBJECT_PADDING = 60
TITLE_FONT_SIZE = 36
OBJECT_FONT_SIZE = 24
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
MIRROR_DEFAULT_SIZE = 100
ROTATION_SPEED = 90

# Degree-entry box
CLICK_MOVE_THRESHOLD = 5  # px of travel below which a press/release counts as a click, not a drag
INPUT_BOX_WIDTH = 180
INPUT_BOX_HEIGHT = 72
INPUT_BOX_MARGIN = 12
INPUT_BOX_FONT_SIZE = 26
INPUT_BOX_LABEL_FONT_SIZE = 18
INPUT_BOX_MAX_CHARS = 8
